// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'6939203e0973f1a0c6199a936bb1bab3d9bd27d4a64486cc5cce620ede802c25'>;
export type ExecutionHash =
  ExecutionHashBase<'abc258c1e537e06409ac342101c62ed883ebc131afbb03a2e143700edb69a010'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Conversation: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly user1Id: CodecTypes['pg/text@1']['output'];
      readonly user2Id: CodecTypes['pg/text@1']['output'];
      readonly topicId: CodecTypes['pg/text@1']['output'];
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly duration: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly GroupDiscussion: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly topicId: CodecTypes['pg/text@1']['output'];
      readonly maxParticipants: CodecTypes['pg/int4@1']['output'];
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly duration: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly GroupParticipant: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly groupDiscussionId: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly joinedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly leftAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly Rating: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly reviewerId: CodecTypes['pg/text@1']['output'];
      readonly reviewedUserId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Topic: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['output'];
      readonly bio: CodecTypes['pg/text@1']['output'] | null;
      readonly interests: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly languageProficiency:
        | 'BEGINNER'
        | 'ELEMENTARY'
        | 'INTERMEDIATE'
        | 'UPPER_INTERMEDIATE'
        | 'ADVANCED'
        | 'PROFICIENT'
        | null;
      readonly rating: CodecTypes['pg/float8@1']['output'] | null;
      readonly totalRatings: CodecTypes['pg/int4@1']['output'] | null;
      readonly isDeleted: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Conversation: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly user1Id: CodecTypes['pg/text@1']['input'];
      readonly user2Id: CodecTypes['pg/text@1']['input'];
      readonly topicId: CodecTypes['pg/text@1']['input'];
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly duration: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly GroupDiscussion: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly topicId: CodecTypes['pg/text@1']['input'];
      readonly maxParticipants: CodecTypes['pg/int4@1']['input'];
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly duration: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly GroupParticipant: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly groupDiscussionId: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly joinedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly leftAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly Rating: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly reviewerId: CodecTypes['pg/text@1']['input'];
      readonly reviewedUserId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Topic: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['input'];
      readonly bio: CodecTypes['pg/text@1']['input'] | null;
      readonly interests: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly languageProficiency:
        | 'BEGINNER'
        | 'ELEMENTARY'
        | 'INTERMEDIATE'
        | 'UPPER_INTERMEDIATE'
        | 'ADVANCED'
        | 'PROFICIENT'
        | null;
      readonly rating: CodecTypes['pg/float8@1']['input'] | null;
      readonly totalRatings: CodecTypes['pg/int4@1']['input'] | null;
      readonly isDeleted: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly conversation: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly duration: CodecTypes['pg/int4@1']['output'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly topicId: CodecTypes['pg/text@1']['output'];
      readonly user1Id: CodecTypes['pg/text@1']['output'];
      readonly user2Id: CodecTypes['pg/text@1']['output'];
    };
    readonly groupDiscussion: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly duration: CodecTypes['pg/int4@1']['output'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly maxParticipants: CodecTypes['pg/int4@1']['output'];
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly topicId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly groupParticipant: {
      readonly groupDiscussionId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly joinedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly leftAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly rating: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly reviewedUserId: CodecTypes['pg/text@1']['output'];
      readonly reviewerId: CodecTypes['pg/text@1']['output'];
    };
    readonly topic: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly user: {
      readonly bio: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly interests: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly isDeleted: CodecTypes['pg/bool@1']['output'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['output'];
      readonly languageProficiency:
        | 'BEGINNER'
        | 'ELEMENTARY'
        | 'INTERMEDIATE'
        | 'UPPER_INTERMEDIATE'
        | 'ADVANCED'
        | 'PROFICIENT'
        | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/float8@1']['output'] | null;
      readonly totalRatings: CodecTypes['pg/int4@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly conversation: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly duration: CodecTypes['pg/int4@1']['input'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly topicId: CodecTypes['pg/text@1']['input'];
      readonly user1Id: CodecTypes['pg/text@1']['input'];
      readonly user2Id: CodecTypes['pg/text@1']['input'];
    };
    readonly groupDiscussion: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly duration: CodecTypes['pg/int4@1']['input'] | null;
      readonly endedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly maxParticipants: CodecTypes['pg/int4@1']['input'];
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly status: 'WAITING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      readonly topicId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly groupParticipant: {
      readonly groupDiscussionId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly joinedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly leftAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly rating: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly reviewedUserId: CodecTypes['pg/text@1']['input'];
      readonly reviewerId: CodecTypes['pg/text@1']['input'];
    };
    readonly topic: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly user: {
      readonly bio: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly interests: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly isDeleted: CodecTypes['pg/bool@1']['input'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['input'];
      readonly languageProficiency:
        | 'BEGINNER'
        | 'ELEMENTARY'
        | 'INTERMEDIATE'
        | 'UPPER_INTERMEDIATE'
        | 'ADVANCED'
        | 'PROFICIENT'
        | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/float8@1']['input'] | null;
      readonly totalRatings: CodecTypes['pg/int4@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly conversation: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly user1Id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly user2Id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly topicId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly endedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly duration: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'conversation_user1Id_idx_db150192';
                  readonly prefix: 'conversation_user1Id_idx';
                  readonly columns: readonly ['user1Id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'conversation_user2Id_idx_d408a8bd';
                  readonly prefix: 'conversation_user2Id_idx';
                  readonly columns: readonly ['user2Id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'conversation_topicId_idx_6f05808f';
                  readonly prefix: 'conversation_topicId_idx';
                  readonly columns: readonly ['topicId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'conversation_status_idx_e98638ab';
                  readonly prefix: 'conversation_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'conversation';
                    readonly columns: readonly ['topicId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'topic';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'conversation';
                    readonly columns: readonly ['user1Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'conversation';
                    readonly columns: readonly ['user2Id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly groupDiscussion: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly topicId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly maxParticipants: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly endedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly duration: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'groupDiscussion_topicId_idx_6f05808f';
                  readonly prefix: 'groupDiscussion_topicId_idx';
                  readonly columns: readonly ['topicId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'groupDiscussion_status_idx_e98638ab';
                  readonly prefix: 'groupDiscussion_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'groupDiscussion';
                    readonly columns: readonly ['topicId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'topic';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly groupParticipant: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly groupDiscussionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly joinedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly leftAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId', 'groupDiscussionId'] }];
              indexes: readonly [
                {
                  readonly name: 'groupParticipant_userId_idx_a489d58a';
                  readonly prefix: 'groupParticipant_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'groupParticipant_groupDiscussionId_idx_772d1f81';
                  readonly prefix: 'groupParticipant_groupDiscussionId_idx';
                  readonly columns: readonly ['groupDiscussionId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'groupParticipant';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'groupParticipant';
                    readonly columns: readonly ['groupDiscussionId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'groupDiscussion';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly rating: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reviewerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reviewedUserId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['reviewerId', 'reviewedUserId'] }];
              indexes: readonly [
                {
                  readonly name: 'rating_reviewerId_idx_25a27b4e';
                  readonly prefix: 'rating_reviewerId_idx';
                  readonly columns: readonly ['reviewerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'rating_reviewedUserId_idx_ad1640bd';
                  readonly prefix: 'rating_reviewedUserId_idx';
                  readonly columns: readonly ['reviewedUserId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rating';
                    readonly columns: readonly ['reviewerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rating';
                    readonly columns: readonly ['reviewedUserId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly topic: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isEmailVerified: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly bio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly interests: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly languageProficiency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly rating: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 0>;
                  };
                };
                readonly totalRatings: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly isDeleted: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['username'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly LanguageProficiency: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'BEGINNER',
                'ELEMENTARY',
                'INTERMEDIATE',
                'UPPER_INTERMEDIATE',
                'ADVANCED',
                'PROFICIENT',
              ];
            };
            readonly SessionStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['WAITING', 'ACTIVE', 'COMPLETED', 'CANCELLED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly rating: { readonly namespace: 'public' & NamespaceId; readonly model: 'Rating' };
    readonly conversation: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Conversation';
    };
    readonly topic: { readonly namespace: 'public' & NamespaceId; readonly model: 'Topic' };
    readonly groupDiscussion: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'GroupDiscussion';
    };
    readonly groupParticipant: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'GroupParticipant';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Conversation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly user1Id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly user2Id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly topicId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly endedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly duration: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly topic: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Topic';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['topicId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user1: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['user1Id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user2: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['user2Id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'conversation';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly user1Id: { readonly column: 'user1Id' };
                readonly user2Id: { readonly column: 'user2Id' };
                readonly topicId: { readonly column: 'topicId' };
                readonly status: { readonly column: 'status' };
                readonly startedAt: { readonly column: 'startedAt' };
                readonly endedAt: { readonly column: 'endedAt' };
                readonly duration: { readonly column: 'duration' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly GroupDiscussion: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly topicId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly maxParticipants: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly endedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly duration: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly groupParticipants: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GroupParticipant';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['groupDiscussionId'];
                };
              };
              readonly topic: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Topic';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['topicId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'groupDiscussion';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly topicId: { readonly column: 'topicId' };
                readonly maxParticipants: { readonly column: 'maxParticipants' };
                readonly status: { readonly column: 'status' };
                readonly startedAt: { readonly column: 'startedAt' };
                readonly endedAt: { readonly column: 'endedAt' };
                readonly duration: { readonly column: 'duration' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly GroupParticipant: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly groupDiscussionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly joinedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly leftAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly groupDiscussion: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GroupDiscussion';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['groupDiscussionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'groupParticipant';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly groupDiscussionId: { readonly column: 'groupDiscussionId' };
                readonly userId: { readonly column: 'userId' };
                readonly joinedAt: { readonly column: 'joinedAt' };
                readonly leftAt: { readonly column: 'leftAt' };
              };
            };
          };
          readonly Rating: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reviewerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reviewedUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly reviewedUser: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['reviewedUserId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly reviewer: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['reviewerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rating';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly rating: { readonly column: 'rating' };
                readonly reviewerId: { readonly column: 'reviewerId' };
                readonly reviewedUserId: { readonly column: 'reviewedUserId' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Topic: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly conversations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Conversation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['topicId'];
                };
              };
              readonly groupDiscussions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GroupDiscussion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['topicId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'topic';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly description: { readonly column: 'description' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isEmailVerified: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly bio: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly interests: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly languageProficiency: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rating: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly totalRatings: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isDeleted: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly conversationsAsUser1: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Conversation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['user1Id'];
                };
              };
              readonly conversationsAsUser2: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Conversation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['user2Id'];
                };
              };
              readonly groupParticipants: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GroupParticipant';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly ratingsGiven: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Rating';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reviewerId'];
                };
              };
              readonly ratingsReceived: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Rating';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reviewedUserId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly username: { readonly column: 'username' };
                readonly name: { readonly column: 'name' };
                readonly password: { readonly column: 'password' };
                readonly isEmailVerified: { readonly column: 'isEmailVerified' };
                readonly bio: { readonly column: 'bio' };
                readonly interests: { readonly column: 'interests' };
                readonly languageProficiency: { readonly column: 'languageProficiency' };
                readonly rating: { readonly column: 'rating' };
                readonly totalRatings: { readonly column: 'totalRatings' };
                readonly isDeleted: { readonly column: 'isDeleted' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly SessionStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'WAITING'; readonly value: 'WAITING' },
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly LanguageProficiency: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'BEGINNER'; readonly value: 'BEGINNER' },
              { readonly name: 'ELEMENTARY'; readonly value: 'ELEMENTARY' },
              { readonly name: 'INTERMEDIATE'; readonly value: 'INTERMEDIATE' },
              { readonly name: 'UPPER_INTERMEDIATE'; readonly value: 'UPPER_INTERMEDIATE' },
              { readonly name: 'ADVANCED'; readonly value: 'ADVANCED' },
              { readonly name: 'PROFICIENT'; readonly value: 'PROFICIENT' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'conversation';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'groupDiscussion';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'groupDiscussion';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'groupParticipant';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'rating';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'topic';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'topic';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
